### PR TITLE
Add Firebase functionality for Badges and fix ProfileView

### LINKED ISSUE #95: Profile view refactoring

### PR DESCRIPTION
**Pull request by JosheevR**
# Add Firebase functionality for Badges and fix ProfileView

## Pulls badges for current user from firebase. Fix UI for ProfileView to more closely match the Figma designs.

### CODE REVIEW

File: Vineyard/Vineyard/ProfileView.swift [hunk 1]
```diff
@@ -11,85 +11,193 @@ struct ProfileView: View {
...
+                                        Spacer().frame(height: 150)
+                                        
+                                        BadgeView(badge: badge)
+                                            .frame(height: 250)
+                                            .padding(.bottom, 15)
+                                        
+                                        VStack {
+                                            Spacer()
+                                            Rectangle()
+                                                .fill(Color(red: 165 / 255, green: 127 / 255, blue: 87 / 255))
```
Comment (sankaet8) [inline Vineyard/Vineyard/ProfileView.swift]: Use Color.purple

File: Vineyard/Vineyard/ProfileView.swift [hunk 2]
```diff
@@ -11,85 +11,193 @@ struct ProfileView: View {
...
+                            .frame(width: 40, height: 140)
+                            .padding()
+                    }
+                    .popover(
+                        isPresented: $showBubble,
+                        attachmentAnchor: .point(.top),
+                        arrowEdge: .bottom
+                    ) {
+                        ZStack {
+                            Color(red: 162/255.0, green: 116/255.0, blue: 218/255.0)
```
Comment (sankaet8) [inline Vineyard/Vineyard/ProfileView.swift:177]: use Color.purple here too

**Review by sankaet8 — COMMENTED** [review]
few nits, please change them. also make the view model for profile

**Review by sankaet8 — APPROVED** [review]
no color purple? view model looks good, feel free to merge
